# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: env
        run: |
          Get-ChildItem ENV:
      shell: pwsh

      - name: Get-ChildItem
        run: |
          Get-ChildItem -Path $GITHUB_WORKSPACE
          Get-ChildItem -Path ${GITHUB_WORKSPACE}/Posh-SysLogger
        shell: pwsh

      - name: Test Module Manifest
        run: |
          ModuleManifest -Path ${GITHUB_WORKSPACE}/Posh-SysLogger/Posh-SysLogger.psd1 -Verbose
        shell: pwsh

      - name: Publish Module to PowerShell Gallery
        run: |
          Publish-Module -Path Posh-SysLogger -NuGetApiKey ${{ secrets.PS_GALLERY_KEY }} -Verbose
        shell: pwsh
